rabbitmq:
  image: rabbitmq:management
  ports:
    - 15672
    - 5672
  environment:
    - RABBITMQ_DEFAULT_USER=emeraldci
    - RABBITMQ_DEFAULT_PASS=secure
    - RABBITMQ_DEFAULT_VHOST=emeraldci
  restart: always
db:
  image: postgres:9.4
  ports:
    - 5432
  environment:
    - POSTGRES_USER=emeraldci
    - POSTGRES_PASSWORD=secure
  restart: always
redis:
  image: redis
  ports:
    - 6379
  restart: always
docker:
  image: emeraldci/docker-socat
  ports:
    - 2375
  privileged: true
  tty: true
  stdin_open: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always
api:
  image: emeraldci/api
  command: api
  ports:
    - 5000
  links:
    - rabbitmq:rabbitmq
    - db:db
    - redis:redis
  environment:
    - RACK_ENV=development
    - SESSION_SECRET=supersavesecret
    - RABBITMQ_URL=amqp://emeraldci:secure@rabbitmq/emeraldci
    - GITHUB_CLIENT_ID=eac688d4a4c1e3ab3d58
    - GITHUB_CLIENT_SECRET=66bd563aae639ca76e5005e8091fe9cfc0efbd44
    - DATABASE_URL=postgres://emeraldci:secure@db/emeraldci
    - REDIS_URL=redis://redis
    - FRONTEND_URL=http://localhost:8080/
  restart: always
worker:
  image: emeraldci/api
  command: worker
  links:
    - db:db
    - redis:redis
    - docker:docker
    - rabbitmq:rabbitmq
  environment:
    - RACK_ENV=development
    - DATABASE_URL=postgres://emeraldci:secure@db/emeraldci
    - RABBITMQ_URL=amqp://emeraldci:secure@rabbitmq/emeraldci
    - REDIS_URL=redis://redis
    - DOCKER_URL=tcp://docker:2375
  restart: always
web:
  image: emeraldci/webapp
  command: grunt serve --port 80
  ports:
    - 80
  restart: always
haproxy:
  image: emeraldci/haproxy
  ports:
    - 80:8080
  links:
    - api:api
    - web:web
  restart: always

